name: Deploy to Server

on:
  push:
    branches:
      - dev  # Укажите ветку, на которую необходимо реагировать

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.16.0'  # Укажите версию Node.js, которую вы используете

      - name: Install dependencies
        run: npm install  # Или npm ci, если у вас есть package-lock.json

      - name: Build the project
        run: npm run build

      - name: Deploy to server
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_LITTLEBEAR }}
          ARGS: "-avz --delete --exclude='.env'"
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.SERVER_HOST }}
          REMOTE_USER: ${{ secrets.SERVER_USER }}
          REMOTE_PORT: "22"
          TARGET: "/var/www/littlebear-dev/"
          SCRIPT_BEFORE: "ls"